---
title: 1918 Flu Pandemic Digital Collection
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://StrikkerGodt.github.io
baseurl: "/1918-Flu-Pandemic"
source-code: https://github.com/StrikkerGodt/1918-Flu-Pandemic
tagline: Exhibit looking at the impact of the 1918 flu on the University of Idaho
description: CollectionBuilder-GH is a template for creating small digital collection
  exhibits on GitHub Pages designed for teaching digital library skills
author: StrikkerGodt
metadata: 1918flu
exclude:
- docs/
- Rakefile
- README.md
- LICENSE
sass:
  style: compressed
